version: '3'

services:
    telegram:
        image: s0288/telegram
        environment:
            - POSTGRES=${POSTGRES}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - RASA_WEBHOOK=${RASA_WEBHOOK}
        networks:
            - aya
    flask:
        image: s0288/flask
        environment:
            - POSTGRES=${POSTGRES}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
        networks:
            - aya
        ports:
            - "5000:5000"
    rasa:
        image: rasa/rasa:1.10.3-full
        environment:
            - AYA_TRACKER_DB_HOST=${AYA_TRACKER_DB_HOST}
            - AYA_TRACKER_DB_DB=${AYA_TRACKER_DB_DB}
            - AYA_TRACKER_DB_USER=${AYA_TRACKER_DB_USER}
            - AYA_TRACKER_DB_PW=${AYA_TRACKER_DB_PW}
        networks:
            - aya
        ports:
            - "5005:5005"
        volumes:
            - ./rasa:/app
        command: 
            - run
            - -vv
        depends_on:
            - actions
    actions:
        image: rasa/rasa-sdk:1.10.1
        networks:
            - aya
        ports:
            - "5055:5055"
        volumes:
            - ./rasa/actions:/app/actions
        command:
            - start
            - --actions
            - actions

networks:
    aya:
